# Generated by Django 5.2.15 on 2026-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
