# Generated by Django 5.2.15 on 2026-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_rename_name_student_firstname_student_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('writed_at', models.DateField()),
            ],
        ),
    ]
